title: orange-lee-tech's Homepage
page-top-title: 李雨橙
top-section-bg-text: Marching Forward 
home-subtitle: '<i class="bi bi-house-fill"></i>&nbsp;主页'
awards-subtitle: '<i class="bi bi-award-fill"></i>&nbsp;获奖简报'
experience-subtitle: '<i class="bi bi-briefcase-fill"></i>&nbsp;工作经历'
publications-subtitle: '<i class="bi bi-file-text-fill"></i>&nbsp;科研与竞赛'

copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
show-images:
  - image1.jpg
  - image2.jpg
  - image3.jpg
  - image4.jpg
  - image5.jpg
  - image6.jpg
  - image7.jpg
  - image8.jpg
person-images:
  - image9.jpg
  - image10.jpg
  - image11.jpg
  - image12.jpg
  - image13.jpg
  - image14.jpg
posts:
  - title: "主页更新"
    date: "2026-01-08"
    file: "posts/2026-01-08-homepage.md"

  - title: "人工智能报考"
    date: "2026-01-09"
    file: "posts/人工智能报考.md"

  - title: "生成式人工智能工程师培训及认证"
    date: "2026-01-10"
    file: "posts/生成式人工智能工程师培训及认证.md"
